hndtools: import x64 binaries built for broadcom routers
Change-Id: I257a3427e07285d3228c5b71543cd12b3465ff67

diff --git a/bin/libtoolize b/bin/libtoolize
--- a/bin/libtoolize
+++ b/bin/libtoolize
@@ -1,5 +1,5 @@
 #! /bin/sh
-# Generated from libtoolize.m4sh by GNU Autoconf 2.65.
+# Generated from libtoolize.m4sh by GNU Autoconf 2.69.
 # Generated from libtoolize.m4sh.
 
 # libtoolize (GNU libtool) 2.2.10
@@ -60,7 +60,7 @@
 # When reporting a bug, please describe a test case to reproduce it and
 # include the following information:
 #
-#       host-triplet:	i686-pc-linux-gnu
+#       host-triplet:	x86_64-unknown-linux-gnu
 #       $progname:	(GNU libtool) 2.2.10
 #       automake:		$automake_version
 #       autoconf:		$autoconf_version
@@ -157,6 +157,7 @@ fi
 IFS=" ""	$as_nl"
 
 # Find who we are.  Look in the path if we contain no directory separator.
+as_myself=
 case $0 in #((
   *[\\/]* ) as_myself=$0 ;;
   *) as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
@@ -234,7 +235,8 @@ if ( set x; as_fn_ret_success y && test x = \"\$1\" ); then :
 else
   exitcode=1; echo positional parameters were not saved.
 fi
-test x\$exitcode = x0 || exit 1"
+test x\$exitcode = x0 || exit 1
+test -x / || exit 1"
   as_suggested=""
   if (eval "$as_required") 2>/dev/null; then :
   as_have_required=yes
@@ -273,14 +275,25 @@ IFS=$as_save_IFS
 
 
       if test "x$CONFIG_SHELL" != x; then :
-  # We cannot yet assume a decent shell, so we have to provide a
-	# neutralization value for shells without unset; and this also
-	# works around shells that cannot unset nonexistent variables.
-	BASH_ENV=/dev/null
-	ENV=/dev/null
-	(unset BASH_ENV) >/dev/null 2>&1 && unset BASH_ENV ENV
-	export CONFIG_SHELL
-	exec "$CONFIG_SHELL" "$as_myself" ${1+"$@"}
+  export CONFIG_SHELL
+             # We cannot yet assume a decent shell, so we have to provide a
+# neutralization value for shells without unset; and this also
+# works around shells that cannot unset nonexistent variables.
+# Preserve -v and -x to the replacement shell.
+BASH_ENV=/dev/null
+ENV=/dev/null
+(unset BASH_ENV) >/dev/null 2>&1 && unset BASH_ENV ENV
+case $- in # ((((
+  *v*x* | *x*v* ) as_opts=-vx ;;
+  *v* ) as_opts=-v ;;
+  *x* ) as_opts=-x ;;
+  * ) as_opts= ;;
+esac
+exec $CONFIG_SHELL $as_opts "$as_myself" ${1+"$@"}
+# Admittedly, this is quite paranoid, since all the known shells bail
+# out after a failed `exec'.
+$as_echo "$0: could not re-execute with $CONFIG_SHELL" >&2
+exit 255
 fi
 
     if test x$as_have_required = xno; then :
